# Generated by Django 4.1.4 on 2023-01-05 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(max_length=50)),
                ('can_be_shared', models.BooleanField(default=True)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(default=None, null=True, upload_to='media_from_users/posts')),
                ('visibility_type', models.IntegerField(choices=[(1, 'Public'), (2, 'Private'), (3, 'Friends')], default=1)),
                ('video', models.FileField(default=None, null=True, upload_to='media_from_users/posts')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('popularity', models.IntegerField(default=0)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_parent', to='posts.post')),
                ('seen_by', models.ManyToManyField(blank=True, related_name='seen_posts', to=settings.AUTH_USER_MODEL)),
                ('shared_from', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='posts.post')),
                ('users_tagged', models.ManyToManyField(blank=True, related_name='users_tagged', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(default=None, null=True)),
                ('answer_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='posts.postcomment')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
        ),
    ]
