# Generated by Django 4.1.4 on 2023-01-05 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_owner_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='owner',
            new_name='author',
        ),
    ]
