# Generated by Django 4.1.4 on 2022-12-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestForImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='test_images')),
            ],
        ),
    ]
