# Generated by Django 4.1.4 on 2022-12-31 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_posts_seen_in_last_24_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactionaction',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='interactions_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interactionaction',
            name='is_active_for_score',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interactionaction',
            name='action',
            field=models.IntegerField(choices=[(1, 'Follow'), (2, 'Unfollow'), (3, 'Block'), (4, 'Unblock'), (5, 'Report'), (6, 'Unreport'), (7, 'Like'), (8, 'Unlike'), (9, 'Add Friend'), (10, 'Remove Friend'), (11, 'Comment'), (12, 'Answer Comment'), (13, 'Delete Comment'), (14, 'Tag')], default=0),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
