# Generated by Django 4.1.4 on 2022-12-31 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_interactions_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactionaction',
            old_name='user',
            new_name='made_by',
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
