# Generated by Django 4.1.4 on 2023-01-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userinteraction_are_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinteraction',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
