# Generated by Django 4.1.4 on 2023-01-03 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_interactionaction_is_first_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinteraction',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
